// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Illuminate.proto

package grpc.IlluminateService;

public final class IlluminateProto {
  private IlluminateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IlluminateService_IlluminateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IlluminateService_IlluminateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IlluminateService_IlluminateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IlluminateService_IlluminateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Illuminate.proto\022\021IlluminateService\"I\n" +
      "\021IlluminateRequest\022\016\n\006farmid\030\001 \001(\005\022\022\n\ndi" +
      "strictid\030\002 \001(\005\022\020\n\010duration\030\003 \001(\005\"6\n\022Illu" +
      "minateResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t2r\n\021IlluminateService\022]\n\nillumin" +
      "ate\022$.IlluminateService.IlluminateReques" +
      "t\032%.IlluminateService.IlluminateResponse" +
      "(\0010\001B+\n\026grpc.IlluminateServiceB\017Illumina" +
      "teProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IlluminateService_IlluminateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IlluminateService_IlluminateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IlluminateService_IlluminateRequest_descriptor,
        new java.lang.String[] { "Farmid", "Districtid", "Duration", });
    internal_static_IlluminateService_IlluminateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_IlluminateService_IlluminateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IlluminateService_IlluminateResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
