// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Illuminage.proto

package grpc.IlluminateService;

public final class IlluminateProto {
  private IlluminateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_illuminate_IluminateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_illuminate_IluminateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_illuminate_IlluminateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_illuminate_IlluminateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Illuminage.proto\022\030com.smartagri.illumi" +
      "nate\"F\n\020IluminateRequest\022\017\n\007farm_id\030\001 \001(" +
      "\t\022\017\n\007zone_id\030\002 \001(\t\022\020\n\010duration\030\003 \001(\t\"6\n\022" +
      "IlluminateResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007m" +
      "essage\030\002 \001(\t2\204\001\n\021IrrigationService\022o\n\017St" +
      "artIrrigation\022*.com.smartagri.illuminate" +
      ".IluminateRequest\032,.com.smartagri.illumi" +
      "nate.IlluminateResponse(\0010\001B+\n\026grpc.Illu" +
      "minateServiceB\017IlluminateProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_smartagri_illuminate_IluminateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartagri_illuminate_IluminateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_illuminate_IluminateRequest_descriptor,
        new java.lang.String[] { "FarmId", "ZoneId", "Duration", });
    internal_static_com_smartagri_illuminate_IlluminateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smartagri_illuminate_IlluminateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_illuminate_IlluminateResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
