// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Illuminate.proto

package grpc.IlluminateService;

public interface IlluminateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IlluminateService.IlluminateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 farmid = 1;</code>
   * @return The farmid.
   */
  int getFarmid();

  /**
   * <code>int32 districtid = 2;</code>
   * @return The districtid.
   */
  int getDistrictid();

  /**
   * <code>int32 duration = 3;</code>
   * @return The duration.
   */
  int getDuration();
}
