// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Irrigation.proto

package grpc.IrrigationService;

public interface IrrigationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartagri.Irrigation.IrrigationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string district = 1;</code>
   * @return The district.
   */
  java.lang.String getDistrict();
  /**
   * <code>string district = 1;</code>
   * @return The bytes for district.
   */
  com.google.protobuf.ByteString
      getDistrictBytes();

  /**
   * <code>string farmid = 2;</code>
   * @return The farmid.
   */
  java.lang.String getFarmid();
  /**
   * <code>string farmid = 2;</code>
   * @return The bytes for farmid.
   */
  com.google.protobuf.ByteString
      getFarmidBytes();
}
