// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Irrigation.proto

package grpc.IrrigationService;

public interface IrrigationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IrrigationService.IrrigationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>int32 volume = 2;</code>
   * @return The volume.
   */
  int getVolume();
}
