// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Irrigation.proto

package grpc.IrrigationService;

public interface IrrigationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartagri.Irrigation.IrrigationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string volume = 2;</code>
   * @return The volume.
   */
  java.lang.String getVolume();
  /**
   * <code>string volume = 2;</code>
   * @return The bytes for volume.
   */
  com.google.protobuf.ByteString
      getVolumeBytes();

  /**
   * <code>double humidity = 3;</code>
   * @return The humidity.
   */
  double getHumidity();
}
