// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Irrigation.proto

package grpc.IrrigationService;

public interface IrrigationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IrrigationService.IrrigationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 districtid = 1;</code>
   * @return The districtid.
   */
  int getDistrictid();

  /**
   * <code>int32 farmid = 2;</code>
   * @return The farmid.
   */
  int getFarmid();
}
