// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Irrigation.proto

package grpc.IrrigationService;

public interface IrrigationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartagri.irrigation.IrrigationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string farm_id = 1;</code>
   * @return The farmId.
   */
  java.lang.String getFarmId();
  /**
   * <code>string farm_id = 1;</code>
   * @return The bytes for farmId.
   */
  com.google.protobuf.ByteString
      getFarmIdBytes();

  /**
   * <code>string zone_id = 2;</code>
   * @return The zoneId.
   */
  java.lang.String getZoneId();
  /**
   * <code>string zone_id = 2;</code>
   * @return The bytes for zoneId.
   */
  com.google.protobuf.ByteString
      getZoneIdBytes();

  /**
   * <code>string duration = 3;</code>
   * @return The duration.
   */
  java.lang.String getDuration();
  /**
   * <code>string duration = 3;</code>
   * @return The bytes for duration.
   */
  com.google.protobuf.ByteString
      getDurationBytes();
}
