// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Irrigation.proto

package grpc.IrrigationService;

/**
 * Protobuf type {@code IrrigationService.IrrigationRequest}
 */
public final class IrrigationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:IrrigationService.IrrigationRequest)
    IrrigationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IrrigationRequest.newBuilder() to construct.
  private IrrigationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IrrigationRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IrrigationRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.IrrigationService.IrrigationProto.internal_static_IrrigationService_IrrigationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.IrrigationService.IrrigationProto.internal_static_IrrigationService_IrrigationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.IrrigationService.IrrigationRequest.class, grpc.IrrigationService.IrrigationRequest.Builder.class);
  }

  public static final int DISTRICTID_FIELD_NUMBER = 1;
  private int districtid_;
  /**
   * <code>int32 districtid = 1;</code>
   * @return The districtid.
   */
  @java.lang.Override
  public int getDistrictid() {
    return districtid_;
  }

  public static final int FARMID_FIELD_NUMBER = 2;
  private int farmid_;
  /**
   * <code>int32 farmid = 2;</code>
   * @return The farmid.
   */
  @java.lang.Override
  public int getFarmid() {
    return farmid_;
  }

  public static final int VOLUME_FIELD_NUMBER = 3;
  private int volume_;
  /**
   * <code>int32 volume = 3;</code>
   * @return The volume.
   */
  @java.lang.Override
  public int getVolume() {
    return volume_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (districtid_ != 0) {
      output.writeInt32(1, districtid_);
    }
    if (farmid_ != 0) {
      output.writeInt32(2, farmid_);
    }
    if (volume_ != 0) {
      output.writeInt32(3, volume_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (districtid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, districtid_);
    }
    if (farmid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, farmid_);
    }
    if (volume_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, volume_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.IrrigationService.IrrigationRequest)) {
      return super.equals(obj);
    }
    grpc.IrrigationService.IrrigationRequest other = (grpc.IrrigationService.IrrigationRequest) obj;

    if (getDistrictid()
        != other.getDistrictid()) return false;
    if (getFarmid()
        != other.getFarmid()) return false;
    if (getVolume()
        != other.getVolume()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISTRICTID_FIELD_NUMBER;
    hash = (53 * hash) + getDistrictid();
    hash = (37 * hash) + FARMID_FIELD_NUMBER;
    hash = (53 * hash) + getFarmid();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getVolume();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.IrrigationService.IrrigationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.IrrigationService.IrrigationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.IrrigationService.IrrigationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.IrrigationService.IrrigationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IrrigationService.IrrigationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IrrigationService.IrrigationRequest)
      grpc.IrrigationService.IrrigationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.IrrigationService.IrrigationProto.internal_static_IrrigationService_IrrigationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.IrrigationService.IrrigationProto.internal_static_IrrigationService_IrrigationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.IrrigationService.IrrigationRequest.class, grpc.IrrigationService.IrrigationRequest.Builder.class);
    }

    // Construct using grpc.IrrigationService.IrrigationRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      districtid_ = 0;

      farmid_ = 0;

      volume_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.IrrigationService.IrrigationProto.internal_static_IrrigationService_IrrigationRequest_descriptor;
    }

    @java.lang.Override
    public grpc.IrrigationService.IrrigationRequest getDefaultInstanceForType() {
      return grpc.IrrigationService.IrrigationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.IrrigationService.IrrigationRequest build() {
      grpc.IrrigationService.IrrigationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.IrrigationService.IrrigationRequest buildPartial() {
      grpc.IrrigationService.IrrigationRequest result = new grpc.IrrigationService.IrrigationRequest(this);
      result.districtid_ = districtid_;
      result.farmid_ = farmid_;
      result.volume_ = volume_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.IrrigationService.IrrigationRequest) {
        return mergeFrom((grpc.IrrigationService.IrrigationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.IrrigationService.IrrigationRequest other) {
      if (other == grpc.IrrigationService.IrrigationRequest.getDefaultInstance()) return this;
      if (other.getDistrictid() != 0) {
        setDistrictid(other.getDistrictid());
      }
      if (other.getFarmid() != 0) {
        setFarmid(other.getFarmid());
      }
      if (other.getVolume() != 0) {
        setVolume(other.getVolume());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              districtid_ = input.readInt32();

              break;
            } // case 8
            case 16: {
              farmid_ = input.readInt32();

              break;
            } // case 16
            case 24: {
              volume_ = input.readInt32();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int districtid_ ;
    /**
     * <code>int32 districtid = 1;</code>
     * @return The districtid.
     */
    @java.lang.Override
    public int getDistrictid() {
      return districtid_;
    }
    /**
     * <code>int32 districtid = 1;</code>
     * @param value The districtid to set.
     * @return This builder for chaining.
     */
    public Builder setDistrictid(int value) {
      
      districtid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 districtid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistrictid() {
      
      districtid_ = 0;
      onChanged();
      return this;
    }

    private int farmid_ ;
    /**
     * <code>int32 farmid = 2;</code>
     * @return The farmid.
     */
    @java.lang.Override
    public int getFarmid() {
      return farmid_;
    }
    /**
     * <code>int32 farmid = 2;</code>
     * @param value The farmid to set.
     * @return This builder for chaining.
     */
    public Builder setFarmid(int value) {
      
      farmid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 farmid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFarmid() {
      
      farmid_ = 0;
      onChanged();
      return this;
    }

    private int volume_ ;
    /**
     * <code>int32 volume = 3;</code>
     * @return The volume.
     */
    @java.lang.Override
    public int getVolume() {
      return volume_;
    }
    /**
     * <code>int32 volume = 3;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(int value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 volume = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      
      volume_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:IrrigationService.IrrigationRequest)
  }

  // @@protoc_insertion_point(class_scope:IrrigationService.IrrigationRequest)
  private static final grpc.IrrigationService.IrrigationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.IrrigationService.IrrigationRequest();
  }

  public static grpc.IrrigationService.IrrigationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IrrigationRequest>
      PARSER = new com.google.protobuf.AbstractParser<IrrigationRequest>() {
    @java.lang.Override
    public IrrigationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IrrigationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IrrigationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.IrrigationService.IrrigationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

