// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Farm.proto

package grpc.FarmService;

public final class FarmProto {
  private FarmProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_farm_FarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_farm_FarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_farm_FarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_farm_FarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_farm_Farm_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_farm_Farm_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nFarm.proto\022\022com.smartagri.farm\032\037google" +
      "/protobuf/timestamp.proto\"K\n\013FarmRequest" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003" +
      " \001(\t\022\020\n\010owner_id\030\004 \001(\t\"X\n\014FarmResponse\022\017" +
      "\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022&\n\004farm" +
      "\030\003 \001(\0132\030.com.smartagri.farm.Farm\"D\n\004Farm" +
      "\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010location\030\003" +
      " \001(\t\022\020\n\010owner_id\030\004 \001(\t2\260\001\n\013FarmService\022L" +
      "\n\007AddFarm\022\037.com.smartagri.farm.FarmReque" +
      "st\032 .com.smartagri.farm.FarmResponse\022S\n\016" +
      "GetFarmDetails\022\037.com.smartagri.farm.Farm" +
      "Request\032 .com.smartagri.farm.FarmRespons" +
      "eB\037\n\020grpc.FarmServiceB\tFarmProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_smartagri_farm_FarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartagri_farm_FarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_farm_FarmRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", "OwnerId", });
    internal_static_com_smartagri_farm_FarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smartagri_farm_FarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_farm_FarmResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Farm", });
    internal_static_com_smartagri_farm_Farm_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_smartagri_farm_Farm_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_farm_Farm_descriptor,
        new java.lang.String[] { "Id", "Name", "Location", "OwnerId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
