// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Farm.proto

package grpc.FarmService;

/**
 * Protobuf type {@code com.smartagri.farm.FarmResponse}
 */
public final class FarmResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.smartagri.farm.FarmResponse)
    FarmResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FarmResponse.newBuilder() to construct.
  private FarmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FarmResponse() {
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FarmResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.FarmService.FarmProto.internal_static_com_smartagri_farm_FarmResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.FarmService.FarmProto.internal_static_com_smartagri_farm_FarmResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.FarmService.FarmResponse.class, grpc.FarmService.FarmResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FARM_FIELD_NUMBER = 3;
  private grpc.FarmService.Farm farm_;
  /**
   * <code>.com.smartagri.farm.Farm farm = 3;</code>
   * @return Whether the farm field is set.
   */
  @java.lang.Override
  public boolean hasFarm() {
    return farm_ != null;
  }
  /**
   * <code>.com.smartagri.farm.Farm farm = 3;</code>
   * @return The farm.
   */
  @java.lang.Override
  public grpc.FarmService.Farm getFarm() {
    return farm_ == null ? grpc.FarmService.Farm.getDefaultInstance() : farm_;
  }
  /**
   * <code>.com.smartagri.farm.Farm farm = 3;</code>
   */
  @java.lang.Override
  public grpc.FarmService.FarmOrBuilder getFarmOrBuilder() {
    return getFarm();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (farm_ != null) {
      output.writeMessage(3, getFarm());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (farm_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFarm());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.FarmService.FarmResponse)) {
      return super.equals(obj);
    }
    grpc.FarmService.FarmResponse other = (grpc.FarmService.FarmResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasFarm() != other.hasFarm()) return false;
    if (hasFarm()) {
      if (!getFarm()
          .equals(other.getFarm())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasFarm()) {
      hash = (37 * hash) + FARM_FIELD_NUMBER;
      hash = (53 * hash) + getFarm().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.FarmService.FarmResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.FarmService.FarmResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.FarmService.FarmResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.FarmService.FarmResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.FarmService.FarmResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.FarmService.FarmResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.FarmService.FarmResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.smartagri.farm.FarmResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.smartagri.farm.FarmResponse)
      grpc.FarmService.FarmResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.FarmService.FarmProto.internal_static_com_smartagri_farm_FarmResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.FarmService.FarmProto.internal_static_com_smartagri_farm_FarmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.FarmService.FarmResponse.class, grpc.FarmService.FarmResponse.Builder.class);
    }

    // Construct using grpc.FarmService.FarmResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      success_ = false;

      message_ = "";

      if (farmBuilder_ == null) {
        farm_ = null;
      } else {
        farm_ = null;
        farmBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.FarmService.FarmProto.internal_static_com_smartagri_farm_FarmResponse_descriptor;
    }

    @java.lang.Override
    public grpc.FarmService.FarmResponse getDefaultInstanceForType() {
      return grpc.FarmService.FarmResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.FarmService.FarmResponse build() {
      grpc.FarmService.FarmResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.FarmService.FarmResponse buildPartial() {
      grpc.FarmService.FarmResponse result = new grpc.FarmService.FarmResponse(this);
      result.success_ = success_;
      result.message_ = message_;
      if (farmBuilder_ == null) {
        result.farm_ = farm_;
      } else {
        result.farm_ = farmBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.FarmService.FarmResponse) {
        return mergeFrom((grpc.FarmService.FarmResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.FarmService.FarmResponse other) {
      if (other == grpc.FarmService.FarmResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasFarm()) {
        mergeFarm(other.getFarm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();

              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getFarmFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private grpc.FarmService.Farm farm_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.FarmService.Farm, grpc.FarmService.Farm.Builder, grpc.FarmService.FarmOrBuilder> farmBuilder_;
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     * @return Whether the farm field is set.
     */
    public boolean hasFarm() {
      return farmBuilder_ != null || farm_ != null;
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     * @return The farm.
     */
    public grpc.FarmService.Farm getFarm() {
      if (farmBuilder_ == null) {
        return farm_ == null ? grpc.FarmService.Farm.getDefaultInstance() : farm_;
      } else {
        return farmBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    public Builder setFarm(grpc.FarmService.Farm value) {
      if (farmBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        farm_ = value;
        onChanged();
      } else {
        farmBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    public Builder setFarm(
        grpc.FarmService.Farm.Builder builderForValue) {
      if (farmBuilder_ == null) {
        farm_ = builderForValue.build();
        onChanged();
      } else {
        farmBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    public Builder mergeFarm(grpc.FarmService.Farm value) {
      if (farmBuilder_ == null) {
        if (farm_ != null) {
          farm_ =
            grpc.FarmService.Farm.newBuilder(farm_).mergeFrom(value).buildPartial();
        } else {
          farm_ = value;
        }
        onChanged();
      } else {
        farmBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    public Builder clearFarm() {
      if (farmBuilder_ == null) {
        farm_ = null;
        onChanged();
      } else {
        farm_ = null;
        farmBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    public grpc.FarmService.Farm.Builder getFarmBuilder() {
      
      onChanged();
      return getFarmFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    public grpc.FarmService.FarmOrBuilder getFarmOrBuilder() {
      if (farmBuilder_ != null) {
        return farmBuilder_.getMessageOrBuilder();
      } else {
        return farm_ == null ?
            grpc.FarmService.Farm.getDefaultInstance() : farm_;
      }
    }
    /**
     * <code>.com.smartagri.farm.Farm farm = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.FarmService.Farm, grpc.FarmService.Farm.Builder, grpc.FarmService.FarmOrBuilder> 
        getFarmFieldBuilder() {
      if (farmBuilder_ == null) {
        farmBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.FarmService.Farm, grpc.FarmService.Farm.Builder, grpc.FarmService.FarmOrBuilder>(
                getFarm(),
                getParentForChildren(),
                isClean());
        farm_ = null;
      }
      return farmBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.smartagri.farm.FarmResponse)
  }

  // @@protoc_insertion_point(class_scope:com.smartagri.farm.FarmResponse)
  private static final grpc.FarmService.FarmResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.FarmService.FarmResponse();
  }

  public static grpc.FarmService.FarmResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FarmResponse>
      PARSER = new com.google.protobuf.AbstractParser<FarmResponse>() {
    @java.lang.Override
    public FarmResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FarmResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FarmResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.FarmService.FarmResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

