// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Farm.proto

package grpc.FarmService;

public interface FarmResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartagri.farm.FarmResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.smartagri.farm.Farm farm = 3;</code>
   * @return Whether the farm field is set.
   */
  boolean hasFarm();
  /**
   * <code>.com.smartagri.farm.Farm farm = 3;</code>
   * @return The farm.
   */
  grpc.FarmService.Farm getFarm();
  /**
   * <code>.com.smartagri.farm.Farm farm = 3;</code>
   */
  grpc.FarmService.FarmOrBuilder getFarmOrBuilder();
}
