// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package grpc.UserService;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_user_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_user_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_user_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_user_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_user_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_user_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smartagri_user_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smartagri_user_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\022com.smartagri.user\"D\n\017Regi" +
      "sterRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010passwor" +
      "d\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"4\n\020RegisterRespon" +
      "se\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"2\n\014" +
      "LoginRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\"@\n\rLoginResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\017\n\007message\030\002 \001(\t\022\r\n\005token\030\003 \001(\t2\262\001\n\013U" +
      "serService\022U\n\010Register\022#.com.smartagri.u" +
      "ser.RegisterRequest\032$.com.smartagri.user" +
      ".RegisterResponse\022L\n\005Login\022 .com.smartag" +
      "ri.user.LoginRequest\032!.com.smartagri.use" +
      "r.LoginResponseB\037\n\020grpc.UserServiceB\tUse" +
      "rProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_smartagri_user_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smartagri_user_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_user_RegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Password", "Email", });
    internal_static_com_smartagri_user_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smartagri_user_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_user_RegisterResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_com_smartagri_user_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_smartagri_user_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_user_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_com_smartagri_user_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_smartagri_user_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smartagri_user_LoginResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
