// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

/**
 * Protobuf type {@code SensorService.AddSensorRequest}
 */
public final class AddSensorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SensorService.AddSensorRequest)
    AddSensorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddSensorRequest.newBuilder() to construct.
  private AddSensorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddSensorRequest() {
    sensortype_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddSensorRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.SensorService.SensorProto.internal_static_SensorService_AddSensorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.SensorService.SensorProto.internal_static_SensorService_AddSensorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.SensorService.AddSensorRequest.class, grpc.SensorService.AddSensorRequest.Builder.class);
  }

  public static final int SENSORID_FIELD_NUMBER = 1;
  private int sensorid_;
  /**
   * <code>int32 sensorid = 1;</code>
   * @return The sensorid.
   */
  @java.lang.Override
  public int getSensorid() {
    return sensorid_;
  }

  public static final int SENSORTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object sensortype_;
  /**
   * <code>string sensortype = 2;</code>
   * @return The sensortype.
   */
  @java.lang.Override
  public java.lang.String getSensortype() {
    java.lang.Object ref = sensortype_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sensortype_ = s;
      return s;
    }
  }
  /**
   * <code>string sensortype = 2;</code>
   * @return The bytes for sensortype.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSensortypeBytes() {
    java.lang.Object ref = sensortype_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sensortype_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISTRICTID_FIELD_NUMBER = 3;
  private int districtid_;
  /**
   * <code>int32 districtid = 3;</code>
   * @return The districtid.
   */
  @java.lang.Override
  public int getDistrictid() {
    return districtid_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sensorid_ != 0) {
      output.writeInt32(1, sensorid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensortype_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sensortype_);
    }
    if (districtid_ != 0) {
      output.writeInt32(3, districtid_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sensorid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, sensorid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sensortype_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sensortype_);
    }
    if (districtid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, districtid_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.SensorService.AddSensorRequest)) {
      return super.equals(obj);
    }
    grpc.SensorService.AddSensorRequest other = (grpc.SensorService.AddSensorRequest) obj;

    if (getSensorid()
        != other.getSensorid()) return false;
    if (!getSensortype()
        .equals(other.getSensortype())) return false;
    if (getDistrictid()
        != other.getDistrictid()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENSORID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorid();
    hash = (37 * hash) + SENSORTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSensortype().hashCode();
    hash = (37 * hash) + DISTRICTID_FIELD_NUMBER;
    hash = (53 * hash) + getDistrictid();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.SensorService.AddSensorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SensorService.AddSensorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.SensorService.AddSensorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SensorService.AddSensorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.SensorService.AddSensorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SensorService.AddSensorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensorService.AddSensorRequest)
      grpc.SensorService.AddSensorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_AddSensorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_AddSensorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.SensorService.AddSensorRequest.class, grpc.SensorService.AddSensorRequest.Builder.class);
    }

    // Construct using grpc.SensorService.AddSensorRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sensorid_ = 0;

      sensortype_ = "";

      districtid_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_AddSensorRequest_descriptor;
    }

    @java.lang.Override
    public grpc.SensorService.AddSensorRequest getDefaultInstanceForType() {
      return grpc.SensorService.AddSensorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.SensorService.AddSensorRequest build() {
      grpc.SensorService.AddSensorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.SensorService.AddSensorRequest buildPartial() {
      grpc.SensorService.AddSensorRequest result = new grpc.SensorService.AddSensorRequest(this);
      result.sensorid_ = sensorid_;
      result.sensortype_ = sensortype_;
      result.districtid_ = districtid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.SensorService.AddSensorRequest) {
        return mergeFrom((grpc.SensorService.AddSensorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.SensorService.AddSensorRequest other) {
      if (other == grpc.SensorService.AddSensorRequest.getDefaultInstance()) return this;
      if (other.getSensorid() != 0) {
        setSensorid(other.getSensorid());
      }
      if (!other.getSensortype().isEmpty()) {
        sensortype_ = other.sensortype_;
        onChanged();
      }
      if (other.getDistrictid() != 0) {
        setDistrictid(other.getDistrictid());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              sensorid_ = input.readInt32();

              break;
            } // case 8
            case 18: {
              sensortype_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              districtid_ = input.readInt32();

              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int sensorid_ ;
    /**
     * <code>int32 sensorid = 1;</code>
     * @return The sensorid.
     */
    @java.lang.Override
    public int getSensorid() {
      return sensorid_;
    }
    /**
     * <code>int32 sensorid = 1;</code>
     * @param value The sensorid to set.
     * @return This builder for chaining.
     */
    public Builder setSensorid(int value) {
      
      sensorid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sensorid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorid() {
      
      sensorid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sensortype_ = "";
    /**
     * <code>string sensortype = 2;</code>
     * @return The sensortype.
     */
    public java.lang.String getSensortype() {
      java.lang.Object ref = sensortype_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensortype_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sensortype = 2;</code>
     * @return The bytes for sensortype.
     */
    public com.google.protobuf.ByteString
        getSensortypeBytes() {
      java.lang.Object ref = sensortype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensortype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensortype = 2;</code>
     * @param value The sensortype to set.
     * @return This builder for chaining.
     */
    public Builder setSensortype(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sensortype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sensortype = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensortype() {
      
      sensortype_ = getDefaultInstance().getSensortype();
      onChanged();
      return this;
    }
    /**
     * <code>string sensortype = 2;</code>
     * @param value The bytes for sensortype to set.
     * @return This builder for chaining.
     */
    public Builder setSensortypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sensortype_ = value;
      onChanged();
      return this;
    }

    private int districtid_ ;
    /**
     * <code>int32 districtid = 3;</code>
     * @return The districtid.
     */
    @java.lang.Override
    public int getDistrictid() {
      return districtid_;
    }
    /**
     * <code>int32 districtid = 3;</code>
     * @param value The districtid to set.
     * @return This builder for chaining.
     */
    public Builder setDistrictid(int value) {
      
      districtid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 districtid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistrictid() {
      
      districtid_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SensorService.AddSensorRequest)
  }

  // @@protoc_insertion_point(class_scope:SensorService.AddSensorRequest)
  private static final grpc.SensorService.AddSensorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.SensorService.AddSensorRequest();
  }

  public static grpc.SensorService.AddSensorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddSensorRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddSensorRequest>() {
    @java.lang.Override
    public AddSensorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AddSensorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddSensorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.SensorService.AddSensorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

