// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

public interface AddSensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensorService.AddSensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sensorid = 1;</code>
   * @return The sensorid.
   */
  int getSensorid();

  /**
   * <code>string sensortype = 2;</code>
   * @return The sensortype.
   */
  java.lang.String getSensortype();
  /**
   * <code>string sensortype = 2;</code>
   * @return The bytes for sensortype.
   */
  com.google.protobuf.ByteString
      getSensortypeBytes();

  /**
   * <code>string location = 3;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
