// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

public interface SensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smartagri.sensor.SensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string unit = 4;</code>
   * @return The unit.
   */
  java.lang.String getUnit();
  /**
   * <code>string unit = 4;</code>
   * @return The bytes for unit.
   */
  com.google.protobuf.ByteString
      getUnitBytes();

  /**
   * <code>string farm_id = 5;</code>
   * @return The farmId.
   */
  java.lang.String getFarmId();
  /**
   * <code>string farm_id = 5;</code>
   * @return The bytes for farmId.
   */
  com.google.protobuf.ByteString
      getFarmIdBytes();
}
