// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

/**
 * Protobuf type {@code SensorService.SensorRequest}
 */
public final class SensorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SensorService.SensorRequest)
    SensorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorRequest.newBuilder() to construct.
  private SensorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SensorRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.SensorService.SensorProto.internal_static_SensorService_SensorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.SensorService.SensorProto.internal_static_SensorService_SensorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.SensorService.SensorRequest.class, grpc.SensorService.SensorRequest.Builder.class);
  }

  public static final int FARMID_FIELD_NUMBER = 1;
  private int farmid_;
  /**
   * <code>int32 farmid = 1;</code>
   * @return The farmid.
   */
  @java.lang.Override
  public int getFarmid() {
    return farmid_;
  }

  public static final int SENSORID_FIELD_NUMBER = 2;
  private int sensorid_;
  /**
   * <code>int32 sensorid = 2;</code>
   * @return The sensorid.
   */
  @java.lang.Override
  public int getSensorid() {
    return sensorid_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (farmid_ != 0) {
      output.writeInt32(1, farmid_);
    }
    if (sensorid_ != 0) {
      output.writeInt32(2, sensorid_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (farmid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, farmid_);
    }
    if (sensorid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, sensorid_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.SensorService.SensorRequest)) {
      return super.equals(obj);
    }
    grpc.SensorService.SensorRequest other = (grpc.SensorService.SensorRequest) obj;

    if (getFarmid()
        != other.getFarmid()) return false;
    if (getSensorid()
        != other.getSensorid()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FARMID_FIELD_NUMBER;
    hash = (53 * hash) + getFarmid();
    hash = (37 * hash) + SENSORID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorid();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.SensorService.SensorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.SensorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.SensorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SensorService.SensorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.SensorService.SensorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SensorService.SensorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.SensorService.SensorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SensorService.SensorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensorService.SensorRequest)
      grpc.SensorService.SensorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_SensorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_SensorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.SensorService.SensorRequest.class, grpc.SensorService.SensorRequest.Builder.class);
    }

    // Construct using grpc.SensorService.SensorRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      farmid_ = 0;

      sensorid_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_SensorRequest_descriptor;
    }

    @java.lang.Override
    public grpc.SensorService.SensorRequest getDefaultInstanceForType() {
      return grpc.SensorService.SensorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.SensorService.SensorRequest build() {
      grpc.SensorService.SensorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.SensorService.SensorRequest buildPartial() {
      grpc.SensorService.SensorRequest result = new grpc.SensorService.SensorRequest(this);
      result.farmid_ = farmid_;
      result.sensorid_ = sensorid_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.SensorService.SensorRequest) {
        return mergeFrom((grpc.SensorService.SensorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.SensorService.SensorRequest other) {
      if (other == grpc.SensorService.SensorRequest.getDefaultInstance()) return this;
      if (other.getFarmid() != 0) {
        setFarmid(other.getFarmid());
      }
      if (other.getSensorid() != 0) {
        setSensorid(other.getSensorid());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              farmid_ = input.readInt32();

              break;
            } // case 8
            case 16: {
              sensorid_ = input.readInt32();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int farmid_ ;
    /**
     * <code>int32 farmid = 1;</code>
     * @return The farmid.
     */
    @java.lang.Override
    public int getFarmid() {
      return farmid_;
    }
    /**
     * <code>int32 farmid = 1;</code>
     * @param value The farmid to set.
     * @return This builder for chaining.
     */
    public Builder setFarmid(int value) {
      
      farmid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 farmid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFarmid() {
      
      farmid_ = 0;
      onChanged();
      return this;
    }

    private int sensorid_ ;
    /**
     * <code>int32 sensorid = 2;</code>
     * @return The sensorid.
     */
    @java.lang.Override
    public int getSensorid() {
      return sensorid_;
    }
    /**
     * <code>int32 sensorid = 2;</code>
     * @param value The sensorid to set.
     * @return This builder for chaining.
     */
    public Builder setSensorid(int value) {
      
      sensorid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sensorid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSensorid() {
      
      sensorid_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SensorService.SensorRequest)
  }

  // @@protoc_insertion_point(class_scope:SensorService.SensorRequest)
  private static final grpc.SensorService.SensorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.SensorService.SensorRequest();
  }

  public static grpc.SensorService.SensorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorRequest>
      PARSER = new com.google.protobuf.AbstractParser<SensorRequest>() {
    @java.lang.Override
    public SensorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.SensorService.SensorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

