// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

public interface SensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensorService.SensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool start = 1;</code>
   * @return The start.
   */
  boolean getStart();
}
