// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

public interface SensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensorService.SensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 farmid = 1;</code>
   * @return The farmid.
   */
  int getFarmid();

  /**
   * <code>int32 sensorid = 2;</code>
   * @return The sensorid.
   */
  int getSensorid();
}
