// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

/**
 * Protobuf type {@code SensorService.SensorResponse}
 */
public final class SensorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SensorService.SensorResponse)
    SensorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SensorResponse.newBuilder() to construct.
  private SensorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SensorResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SensorResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.SensorService.SensorProto.internal_static_SensorService_SensorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.SensorService.SensorProto.internal_static_SensorService_SensorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.SensorService.SensorResponse.class, grpc.SensorService.SensorResponse.Builder.class);
  }

  public static final int TEMPRETURE_FIELD_NUMBER = 1;
  private double tempreture_;
  /**
   * <code>double tempreture = 1;</code>
   * @return The tempreture.
   */
  @java.lang.Override
  public double getTempreture() {
    return tempreture_;
  }

  public static final int HUMIDITY_FIELD_NUMBER = 2;
  private int humidity_;
  /**
   * <code>int32 humidity = 2;</code>
   * @return The humidity.
   */
  @java.lang.Override
  public int getHumidity() {
    return humidity_;
  }

  public static final int DISTRICTID_FIELD_NUMBER = 3;
  private int districtid_;
  /**
   * <code>int32 districtid = 3;</code>
   * @return The districtid.
   */
  @java.lang.Override
  public int getDistrictid() {
    return districtid_;
  }

  public static final int ILLUMINATION_FIELD_NUMBER = 4;
  private int illumination_;
  /**
   * <code>int32 illumination = 4;</code>
   * @return The illumination.
   */
  @java.lang.Override
  public int getIllumination() {
    return illumination_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(tempreture_) != 0) {
      output.writeDouble(1, tempreture_);
    }
    if (humidity_ != 0) {
      output.writeInt32(2, humidity_);
    }
    if (districtid_ != 0) {
      output.writeInt32(3, districtid_);
    }
    if (illumination_ != 0) {
      output.writeInt32(4, illumination_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(tempreture_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, tempreture_);
    }
    if (humidity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, humidity_);
    }
    if (districtid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, districtid_);
    }
    if (illumination_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, illumination_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.SensorService.SensorResponse)) {
      return super.equals(obj);
    }
    grpc.SensorService.SensorResponse other = (grpc.SensorService.SensorResponse) obj;

    if (java.lang.Double.doubleToLongBits(getTempreture())
        != java.lang.Double.doubleToLongBits(
            other.getTempreture())) return false;
    if (getHumidity()
        != other.getHumidity()) return false;
    if (getDistrictid()
        != other.getDistrictid()) return false;
    if (getIllumination()
        != other.getIllumination()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPRETURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTempreture()));
    hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
    hash = (53 * hash) + getHumidity();
    hash = (37 * hash) + DISTRICTID_FIELD_NUMBER;
    hash = (53 * hash) + getDistrictid();
    hash = (37 * hash) + ILLUMINATION_FIELD_NUMBER;
    hash = (53 * hash) + getIllumination();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.SensorService.SensorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.SensorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.SensorService.SensorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SensorService.SensorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.SensorService.SensorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.SensorService.SensorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.SensorService.SensorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SensorService.SensorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SensorService.SensorResponse)
      grpc.SensorService.SensorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_SensorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_SensorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.SensorService.SensorResponse.class, grpc.SensorService.SensorResponse.Builder.class);
    }

    // Construct using grpc.SensorService.SensorResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tempreture_ = 0D;

      humidity_ = 0;

      districtid_ = 0;

      illumination_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.SensorService.SensorProto.internal_static_SensorService_SensorResponse_descriptor;
    }

    @java.lang.Override
    public grpc.SensorService.SensorResponse getDefaultInstanceForType() {
      return grpc.SensorService.SensorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.SensorService.SensorResponse build() {
      grpc.SensorService.SensorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.SensorService.SensorResponse buildPartial() {
      grpc.SensorService.SensorResponse result = new grpc.SensorService.SensorResponse(this);
      result.tempreture_ = tempreture_;
      result.humidity_ = humidity_;
      result.districtid_ = districtid_;
      result.illumination_ = illumination_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.SensorService.SensorResponse) {
        return mergeFrom((grpc.SensorService.SensorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.SensorService.SensorResponse other) {
      if (other == grpc.SensorService.SensorResponse.getDefaultInstance()) return this;
      if (other.getTempreture() != 0D) {
        setTempreture(other.getTempreture());
      }
      if (other.getHumidity() != 0) {
        setHumidity(other.getHumidity());
      }
      if (other.getDistrictid() != 0) {
        setDistrictid(other.getDistrictid());
      }
      if (other.getIllumination() != 0) {
        setIllumination(other.getIllumination());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              tempreture_ = input.readDouble();

              break;
            } // case 9
            case 16: {
              humidity_ = input.readInt32();

              break;
            } // case 16
            case 24: {
              districtid_ = input.readInt32();

              break;
            } // case 24
            case 32: {
              illumination_ = input.readInt32();

              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private double tempreture_ ;
    /**
     * <code>double tempreture = 1;</code>
     * @return The tempreture.
     */
    @java.lang.Override
    public double getTempreture() {
      return tempreture_;
    }
    /**
     * <code>double tempreture = 1;</code>
     * @param value The tempreture to set.
     * @return This builder for chaining.
     */
    public Builder setTempreture(double value) {
      
      tempreture_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double tempreture = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTempreture() {
      
      tempreture_ = 0D;
      onChanged();
      return this;
    }

    private int humidity_ ;
    /**
     * <code>int32 humidity = 2;</code>
     * @return The humidity.
     */
    @java.lang.Override
    public int getHumidity() {
      return humidity_;
    }
    /**
     * <code>int32 humidity = 2;</code>
     * @param value The humidity to set.
     * @return This builder for chaining.
     */
    public Builder setHumidity(int value) {
      
      humidity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 humidity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHumidity() {
      
      humidity_ = 0;
      onChanged();
      return this;
    }

    private int districtid_ ;
    /**
     * <code>int32 districtid = 3;</code>
     * @return The districtid.
     */
    @java.lang.Override
    public int getDistrictid() {
      return districtid_;
    }
    /**
     * <code>int32 districtid = 3;</code>
     * @param value The districtid to set.
     * @return This builder for chaining.
     */
    public Builder setDistrictid(int value) {
      
      districtid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 districtid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDistrictid() {
      
      districtid_ = 0;
      onChanged();
      return this;
    }

    private int illumination_ ;
    /**
     * <code>int32 illumination = 4;</code>
     * @return The illumination.
     */
    @java.lang.Override
    public int getIllumination() {
      return illumination_;
    }
    /**
     * <code>int32 illumination = 4;</code>
     * @param value The illumination to set.
     * @return This builder for chaining.
     */
    public Builder setIllumination(int value) {
      
      illumination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 illumination = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIllumination() {
      
      illumination_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SensorService.SensorResponse)
  }

  // @@protoc_insertion_point(class_scope:SensorService.SensorResponse)
  private static final grpc.SensorService.SensorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.SensorService.SensorResponse();
  }

  public static grpc.SensorService.SensorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SensorResponse>
      PARSER = new com.google.protobuf.AbstractParser<SensorResponse>() {
    @java.lang.Override
    public SensorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SensorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SensorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.SensorService.SensorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

