// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

public final class SensorProto {
  private SensorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorService_SensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SensorService_SensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorService_SensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SensorService_SensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorService_AddSensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SensorService_AddSensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SensorService_AddSensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SensorService_AddSensorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Sensor.proto\022\rSensorService\"1\n\rSensorR" +
      "equest\022\016\n\006farmid\030\001 \001(\005\022\020\n\010sensorid\030\002 \001(\005" +
      "\"^\n\016SensorResponse\022\022\n\ntempreture\030\001 \001(\001\022\020" +
      "\n\010humidity\030\002 \001(\001\022\020\n\010district\030\003 \001(\t\022\024\n\014il" +
      "lumination\030\004 \001(\001\"J\n\020AddSensorRequest\022\020\n\010" +
      "sensorid\030\001 \001(\005\022\022\n\nsensortype\030\002 \001(\t\022\020\n\010lo" +
      "cation\030\003 \001(\t\"5\n\021AddSensorResponse\022\017\n\007suc" +
      "cess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\262\001\n\rSensorSe" +
      "rvice\022Q\n\020StreamSensorData\022\034.SensorServic" +
      "e.SensorRequest\032\035.SensorService.SensorRe" +
      "sponse0\001\022N\n\tAddSensor\022\037.SensorService.Ad" +
      "dSensorRequest\032 .SensorService.AddSensor" +
      "ResponseB#\n\022grpc.SensorServiceB\013SensorPr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SensorService_SensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SensorService_SensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SensorService_SensorRequest_descriptor,
        new java.lang.String[] { "Farmid", "Sensorid", });
    internal_static_SensorService_SensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SensorService_SensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SensorService_SensorResponse_descriptor,
        new java.lang.String[] { "Tempreture", "Humidity", "District", "Illumination", });
    internal_static_SensorService_AddSensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SensorService_AddSensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SensorService_AddSensorRequest_descriptor,
        new java.lang.String[] { "Sensorid", "Sensortype", "Location", });
    internal_static_SensorService_AddSensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SensorService_AddSensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SensorService_AddSensorResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
