// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sensor.proto

package grpc.SensorService;

public interface SensorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SensorService.SensorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 farmid = 1;</code>
   * @return The farmid.
   */
  int getFarmid();

  /**
   * <code>int32 sensorid = 2;</code>
   * @return The sensorid.
   */
  int getSensorid();

  /**
   * <code>int32 districtid = 3;</code>
   * @return The districtid.
   */
  int getDistrictid();

  /**
   * <code>double tempreture = 4;</code>
   * @return The tempreture.
   */
  double getTempreture();

  /**
   * <code>int32 humidity = 5;</code>
   * @return The humidity.
   */
  int getHumidity();

  /**
   * <code>int32 illumination = 6;</code>
   * @return The illumination.
   */
  int getIllumination();
}
